### ISSUE TITLE
CORS support on /profile

### ISSUE THREAD

**Issue by pkkummermo** [telenordigital/goconnect#2]
The `<path>/profile` endpoint will most likely be called by something async and sometimes the API/Auth server is on another domain meaning we need CORS. Add the usual CORS headers, ie

- `Access-Control-Allow-Origin` with the correct origin
- `Access-Control-Allow-Methods` with GET
- `Access-Control-Allow-Credentials` to true

**Comment by stalehd** [comment]
The endpoint wrapped in the auth handler will provide these headers.
